# Generated by Django 4.0.3 on 2022-03-23 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('No', models.IntegerField()),
                ('Name', models.CharField(max_length=25)),
                ('Age', models.IntegerField()),
                ('Mob', models.IntegerField()),
                ('Add', models.CharField(max_length=64)),
            ],
        ),
    ]
